title:               Serving Circuits
url:                 https://servingcircuits.blog
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Aram Akhavan
  url:               servingcircuits.blog
  email:             contact@servingcircuits.blog

google_analytics: G-SVFFHP63KD

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
